CREATE TABLE production_item_demand (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  production_batch_id BIGINT UNSIGNED NOT NULL,
  product_material_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  quantity_per_unit_snapshot DECIMAL(12,4) NOT NULL,
  unit_snapshot VARCHAR(20) NOT NULL,
  is_key_material_snapshot TINYINT NOT NULL,
  need_batch_record_snapshot TINYINT NOT NULL,
  planned_output_quantity_snapshot DECIMAL(12,4) NOT NULL,
  need_number DECIMAL(12,4) NOT NULL,
  demand_type TINYINT NOT NULL DEFAULT 0,
  idempotency_key VARCHAR(150) NOT NULL,
  parent_demand_id BIGINT UNSIGNED NULL,
  source_scrap_id BIGINT UNSIGNED NULL,
  reason_type VARCHAR(50) NULL,
  business_status VARCHAR(30) NOT NULL DEFAULT 'active',
  version INT NOT NULL DEFAULT 0,
  remark TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_production_item_demand_idempotency (idempotency_key),
  UNIQUE KEY uk_production_item_demand_item_reference (id, item_id),
  UNIQUE KEY uk_production_item_demand_batch_reference (id, production_batch_id),
  KEY idx_production_item_demand_batch_status (production_batch_id, business_status),
  CONSTRAINT chk_production_item_demand_quantity CHECK (quantity_per_unit_snapshot > 0 AND planned_output_quantity_snapshot > 0 AND need_number > 0),
  CONSTRAINT chk_production_item_demand_flags CHECK (is_key_material_snapshot IN (0, 1) AND need_batch_record_snapshot IN (0, 1)),
  CONSTRAINT chk_production_item_demand_type CHECK (demand_type = 0),
  CONSTRAINT chk_production_item_demand_status CHECK (business_status IN ('active', 'cancelled', 'closed', 'frozen', 'abnormal')),
  CONSTRAINT chk_production_item_demand_normal CHECK (parent_demand_id IS NULL AND source_scrap_id IS NULL),
  CONSTRAINT chk_production_item_demand_version CHECK (version >= 0),
  CONSTRAINT fk_production_item_demand_batch FOREIGN KEY (production_batch_id) REFERENCES production_batches(id),
  CONSTRAINT fk_production_item_demand_material FOREIGN KEY (product_material_id, item_id) REFERENCES product_materials(id, material_product_id),
  CONSTRAINT fk_production_item_demand_item FOREIGN KEY (item_id) REFERENCES products(id),
  CONSTRAINT fk_production_item_demand_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_production_item_demand_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
