CREATE TABLE item_batch (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_id BIGINT UNSIGNED NOT NULL,
  item_code_snapshot VARCHAR(100) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  unit_snapshot VARCHAR(20) NOT NULL,
  batch_code VARCHAR(100) NOT NULL,
  source_type VARCHAR(30) NOT NULL,
  provider VARCHAR(100) NULL,
  source_work_order_id BIGINT UNSIGNED NULL,
  source_production_batch_id BIGINT UNSIGNED NULL,
  production_date DATE NULL,
  batch_status VARCHAR(20) NOT NULL DEFAULT 'available',
  remark TEXT NULL,
  version INT NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_item_batch_item_code (item_id, batch_code),
  UNIQUE KEY uk_item_batch_id_item (id, item_id),
  KEY idx_item_batch_item_status (item_id, batch_status),
  CONSTRAINT chk_item_batch_source_type CHECK (source_type IN ('self_made','purchased','outsourced','return_inbound','stock_check_generated','other')),
  CONSTRAINT chk_item_batch_status CHECK (batch_status IN ('available','frozen','disabled')),
  CONSTRAINT chk_item_batch_version CHECK (version >= 0),
  CONSTRAINT fk_item_batch_item FOREIGN KEY (item_id) REFERENCES products(id),
  CONSTRAINT fk_item_batch_source_work_order FOREIGN KEY (source_work_order_id) REFERENCES work_orders(id),
  CONSTRAINT fk_item_batch_source_production FOREIGN KEY (source_production_batch_id, source_work_order_id) REFERENCES production_batches(id, work_order_id),
  CONSTRAINT fk_item_batch_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_item_batch_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE production_item_allocation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  demand_id BIGINT UNSIGNED NOT NULL,
  production_batch_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  assigned_number DECIMAL(12,4) NOT NULL,
  unit_snapshot VARCHAR(20) NOT NULL,
  allocation_status VARCHAR(30) NOT NULL DEFAULT 'active',
  version INT NOT NULL DEFAULT 0,
  remark TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_production_item_allocation_id_demand (id, demand_id),
  UNIQUE KEY uk_production_item_allocation_id_batch (id, production_batch_id),
  UNIQUE KEY uk_production_item_allocation_id_item (id, item_id),
  UNIQUE KEY uk_production_item_allocation_reference (id, demand_id, production_batch_id, item_id, batch_id),
  KEY idx_production_item_allocation_batch_status (production_batch_id, allocation_status),
  KEY idx_production_item_allocation_stock_batch (batch_id, allocation_status),
  CONSTRAINT chk_production_item_allocation_quantity CHECK (assigned_number > 0),
  CONSTRAINT chk_production_item_allocation_status CHECK (allocation_status IN ('active','released','cancelled','frozen','abnormal')),
  CONSTRAINT chk_production_item_allocation_version CHECK (version >= 0),
  CONSTRAINT fk_production_item_allocation_demand_item FOREIGN KEY (demand_id, item_id) REFERENCES production_item_demand(id, item_id),
  CONSTRAINT fk_production_item_allocation_demand_batch FOREIGN KEY (demand_id, production_batch_id) REFERENCES production_item_demand(id, production_batch_id),
  CONSTRAINT fk_production_item_allocation_stock_batch FOREIGN KEY (batch_id, item_id) REFERENCES item_batch(id, item_id),
  CONSTRAINT fk_production_item_allocation_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_production_item_allocation_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbound_order (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  outbound_no VARCHAR(100) NOT NULL,
  production_batch_id BIGINT UNSIGNED NOT NULL,
  work_order_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending_picking',
  outbound_at DATETIME NULL,
  operator_id BIGINT UNSIGNED NOT NULL,
  version INT NOT NULL DEFAULT 0,
  remark TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT UNSIGNED NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_outbound_order_no (outbound_no),
  UNIQUE KEY uk_outbound_order_id_batch (id, production_batch_id),
  KEY idx_outbound_order_status_created (status, created_at),
  KEY idx_outbound_order_batch_created (production_batch_id, created_at),
  CONSTRAINT chk_outbound_order_status CHECK (status IN ('pending_picking','picked','partially_outbound','completed','cancelled')),
  CONSTRAINT chk_outbound_order_version CHECK (version >= 0),
  CONSTRAINT fk_outbound_order_batch_work_order FOREIGN KEY (production_batch_id, work_order_id) REFERENCES production_batches(id, work_order_id),
  CONSTRAINT fk_outbound_order_operator FOREIGN KEY (operator_id) REFERENCES users(id),
  CONSTRAINT fk_outbound_order_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_outbound_order_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbound_detail (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  outbound_id BIGINT UNSIGNED NOT NULL,
  production_batch_id BIGINT UNSIGNED NOT NULL,
  demand_id BIGINT UNSIGNED NOT NULL,
  allocation_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  outbound_number DECIMAL(12,4) NOT NULL,
  unit_snapshot VARCHAR(20) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_outbound_detail_order_allocation (outbound_id, allocation_id),
  KEY idx_outbound_detail_demand (demand_id, created_at),
  KEY idx_outbound_detail_allocation (allocation_id, created_at),
  CONSTRAINT chk_outbound_detail_quantity CHECK (outbound_number > 0),
  CONSTRAINT fk_outbound_detail_order_batch FOREIGN KEY (outbound_id, production_batch_id) REFERENCES outbound_order(id, production_batch_id),
  CONSTRAINT fk_outbound_detail_demand_batch FOREIGN KEY (demand_id, production_batch_id) REFERENCES production_item_demand(id, production_batch_id),
  CONSTRAINT fk_outbound_detail_allocation FOREIGN KEY (allocation_id, demand_id, production_batch_id, item_id, batch_id) REFERENCES production_item_allocation(id, demand_id, production_batch_id, item_id, batch_id),
  CONSTRAINT fk_outbound_detail_stock_batch FOREIGN KEY (batch_id, item_id) REFERENCES item_batch(id, item_id),
  CONSTRAINT fk_outbound_detail_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inventory_transaction (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  transaction_type VARCHAR(30) NOT NULL,
  quantity DECIMAL(12,4) NOT NULL,
  unit_snapshot VARCHAR(20) NOT NULL,
  stock_status VARCHAR(20) NOT NULL DEFAULT 'available',
  reference_type VARCHAR(50) NOT NULL,
  reference_detail_id BIGINT UNSIGNED NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL,
  transaction_group_key VARCHAR(150) NULL,
  reversal_of_transaction_id BIGINT UNSIGNED NULL,
  remark TEXT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_inventory_transaction_idempotency (idempotency_key),
  UNIQUE KEY uk_inventory_transaction_reversal (reversal_of_transaction_id),
  KEY idx_inventory_transaction_group (transaction_group_key),
  KEY idx_inventory_transaction_stock (item_id, batch_id, stock_status, created_at),
  KEY idx_inventory_transaction_reference (reference_type, reference_detail_id),
  CONSTRAINT chk_inventory_transaction_quantity CHECK (quantity <> 0),
  CONSTRAINT chk_inventory_transaction_type CHECK (transaction_type IN ('purchase_inbound','production_inbound','outsourced_inbound','production_material_outbound','sales_outbound','material_return_inbound','scrap_outbound','stock_check_adjustment','status_transfer_in','status_transfer_out')),
  CONSTRAINT chk_inventory_transaction_stock_status CHECK (stock_status IN ('available','pending_inspection','frozen','defective')),
  CONSTRAINT fk_inventory_transaction_item FOREIGN KEY (item_id) REFERENCES products(id),
  CONSTRAINT fk_inventory_transaction_batch_item FOREIGN KEY (batch_id, item_id) REFERENCES item_batch(id, item_id),
  CONSTRAINT fk_inventory_transaction_reversal FOREIGN KEY (reversal_of_transaction_id) REFERENCES inventory_transaction(id),
  CONSTRAINT fk_inventory_transaction_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO permissions (parent_id, name, code, type, route_path, api_method, api_path, sort_order, status)
SELECT id, '查看生产物料', 'production:materials:view', 'api', NULL, 'GET', '/api/production/batches/:batchId/material-demands', 226, 1 FROM permissions WHERE code='production:view'
UNION ALL SELECT id, '分配生产物料', 'production:materials:allocate', 'api', NULL, 'POST', '/api/production/batches/:batchId/material-allocations*', 227, 1 FROM permissions WHERE code='production:view'
UNION ALL SELECT id, '生产领料出库', 'production:materials:outbound', 'api', NULL, 'POST', '/api/production/batches/:batchId/material-outbounds', 228, 1 FROM permissions WHERE code='production:view'
ON DUPLICATE KEY UPDATE parent_id=VALUES(parent_id), name=VALUES(name), type=VALUES(type), route_path=VALUES(route_path), api_method=VALUES(api_method), api_path=VALUES(api_path), sort_order=VALUES(sort_order), status=1, deleted_at=NULL;
