export class ProductionDomainError extends Error {
  constructor(
    readonly code:
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'INVALID_STATE'
      | 'INVALID_INPUT'
      | 'CONCURRENT_MODIFICATION'
      | 'WORK_ORDER_COMPLETION_NOT_ALLOWED'
      | 'WORK_ORDER_CLOSE_NOT_ALLOWED'
      | 'BATCH_CANCEL_NOT_ALLOWED'
      | 'INSUFFICIENT_AVAILABLE_STOCK'
      | 'ALLOCATION_EXCEEDS_DEMAND'
      | 'ALLOCATION_ALREADY_OUTBOUND'
      | 'ALLOCATION_PENDING_OUTBOUND'
      | 'OUTBOUND_EXCEEDS_ALLOCATION'
      | 'OUTBOUND_ALLOCATION_CHANGED'
      | 'OUTBOUND_CONFIRM_NOT_ALLOWED'
      | 'OUTBOUND_CANCEL_NOT_ALLOWED'
      | 'SHORT_BATCH_AUTHORIZATION_NOT_ALLOWED'
      | 'SHORT_BATCH_AUTHORIZATION_STALE'
      | 'INBOUND_CONFIRM_NOT_ALLOWED'
      | 'INBOUND_CANCEL_NOT_ALLOWED'
      | 'RETURN_QUANTITY_EXCEEDED'
      | 'RETURN_CONFIRM_NOT_ALLOWED'
      | 'RETURN_CANCEL_NOT_ALLOWED'
      | 'SCRAP_QUANTITY_EXCEEDED'
      | 'SCRAP_CONFIRM_NOT_ALLOWED'
      | 'SCRAP_CANCEL_NOT_ALLOWED'
      | 'STOCK_CHECK_COUNT_NOT_ALLOWED'
      | 'STOCK_CHECK_INCOMPLETE'
      | 'STOCK_CHECK_SNAPSHOT_CHANGED'
      | 'STOCK_CHECK_CANCEL_NOT_ALLOWED'
      | 'STEP_ASSIGNMENT_CONFLICT'
      | 'STEP_START_NOT_ALLOWED'
      | 'STEP_COMPLETION_NOT_ALLOWED'
      | 'NOT_STEP_ASSIGNEE'
      | 'STEP_REPORT_NOT_ALLOWED'
      | 'STEP_REPORT_QUANTITY_EXCEEDED'
      | 'STEP_REPORT_ALREADY_REVERSED'
      | 'STEP_REPORT_DEPENDENCY_CONFLICT'
      | 'DOWNSTREAM_QUANTITY_CONFLICT'
      | 'BATCH_EXECUTION_COMPLETION_NOT_ALLOWED'
      | 'NO_REQUIRED_REPORTING_STEP'
      | 'REQUIRED_STEP_INCOMPLETE'
      | 'FINAL_STEP_QUANTITY_INSUFFICIENT'
      | 'ACTIVE_MATERIAL_DEMAND_REMAINS'
      | 'SOP_SNAPSHOT_UNAVAILABLE',
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
  }
}
